name: Add to Project

on:
  issues:
    types: [ opened ]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to Project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/JayFilker/projects/4
          github-token: ${{ secrets.TOKEN }}
